-   id: powershell-scriptanalyzer-docker
    name: PSScriptAnalyzer (docker)
    description: PSScriptAnalyzer, provided by docker
    entry: pwsh -c Import-Module PSScriptAnalyzer; Invoke-ScriptAnalyzer -ScriptDefinition
    language: docker
    files: \.ps1$
