-   id: powershell-scriptanalyzer-docker
    name: PSScriptAnalyzer (docker)
    description: PSScriptAnalyzer, provided by docker
    entry: pwsh -c Invoke-ScriptAnalyzer -Fix -Path
    language: docker
    files: \.ps1$
